name: Update Test IDs

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'packages/otterfall/**/*.spec.ts'
      - 'packages/otterfall/**/*.test.ts'

jobs:
  update-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      # actions/checkout v6.0.1
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Node.js
      # actions/setup-node v6.1.0
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
      with:
        node-version: '22'

    - name: Import tests and update IDs
      run: npx check-tests@latest Playwright "packages/otterfall/**/*{.,_}{test,spec}.ts" --update-ids --typescript
      env:
        TESTOMATIO: ${{ secrets.TESTOMATIO }}

    - name: Commit and push changes
      # stefanzweifel/git-auto-commit-action v7.0.0
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3
      with:
        commit_message: "chore: Update Testomat.io test IDs"
        file_pattern: "packages/otterfall/**/*.ts"
