name: Update Test IDs

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'packages/otterfall/**/*.spec.ts'
      - 'packages/otterfall/**/*.test.ts'

jobs:
  update-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # actions/checkout v4.3.1
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Node.js
      # actions/setup-node v4.4.0
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: '22'

    - name: Import tests and update IDs
      run: npx check-tests@latest Playwright "packages/otterfall/**/*{.,_}{test,spec}.ts" --update-ids --typescript
      env:
        TESTOMATIO: ${{ secrets.TESTOMATIO }}

    - name: Commit and push changes
      # stefanzweifel/git-auto-commit-action v5.2.0
      uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
      with:
        commit_message: "chore: Update Testomat.io test IDs"
        file_pattern: "packages/otterfall/**/*.ts"
